name: deploy-auth

on: 
  push:
    branches: 
      -master
    paths: 
      - 'auth/**'
      
jobs:
  build:
    runs-on: ubunto-latest
    steps: 
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t 080714/auth . 
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}   
      - run: docker push 080714/auth 
      - uses: digitalocean/action-doctl@v2
        with: 
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}      
      - run: doctl kubernetes cluster kubeconfig save ticketing

